version: '2'
services:
    mymicroapp-mongodb:
        container_name: mymicroapp-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/mymicroapp/mongodb/:/data/db/
