version: '2'
services:
    mymicroapp-mongodb:
        container_name: mymicroapp-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb mymicroapp-mongodb-config
    mymicroapp-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    mymicroapp-mongodb-config:
        image: mongo:3.2.10
        container_name: mymicroapp-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
